version: build.{build}

branches:
  only:
    - master

shallow_clone: true

os: Visual Studio 2017

platform: x64
configuration: Release

build:
  project: build\projects\windows\mametiny\vs2017\mametiny.sln
  
