version: build.{build}

branches:
  only:
    - master

os: Visual Studio 2015

platform: x64
configuration: Release

clone_folder: c:\src\milliluk\mame

build:
  project: c:\src\milliluk\mame\build\projects\windows\mametiny\vs2015\mametiny.sln

